handlers= java.util.logging.ConsoleHandler
.level= INFO

java.util.logging.ConsoleHandler.level = INFO
java.util.logging.ConsoleHandler.formatter = java.util.logging.SimpleFormatter

# Formato do SimpleFormatter:
# %1$tF %1$tT = data/hora; %4$s = level; %3$s = logger; %5$s = mensagem; %6$s = stacktrace
# Abaixo, apenas nível e mensagem:
java.util.logging.SimpleFormatter.format=%4$s: %5$s%n